trigger:
  branches:
    include:
    - '*'

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    echo Sync azure repo
    B64_PAT=$(echo -n ":$PAT" | base64)
    git -c http.extraHeader="Authorization: Basic ${B64_PAT}" clone --bare https://dev.azure.com/tbs-sct/GCExchange/_git/$REPO_NAME Sync_directory
    cd Sync_directory
    git remote add --mirror=fetch upstream https://github.com/gcxchange-gcechange/$REPO_NAME
    git fetch upstream --tags
    git -c http.extraHeader="Authorization: Basic ${B64_PAT}" push origin --all
  env:
    PAT: $(PAT)
    REPO_NAME: "/SCW_Admin"
  displayName: 'Sync repo'
